import * as Expected from '@tanstack/react-query';
import type { Context, OctaneNode, JSX } from 'octane';

export interface ExpectedContracts {
	AnyUseBaseQueryOptions_1: Expected.AnyUseBaseQueryOptions;
	AnyUseInfiniteQueryOptions_1: Expected.AnyUseInfiniteQueryOptions;
	AnyUseMutationOptions_1: Expected.AnyUseMutationOptions;
	AnyUseQueryOptions_1: Expected.AnyUseQueryOptions;
	AnyUseSuspenseInfiniteQueryOptions_1: Expected.AnyUseSuspenseInfiniteQueryOptions;
	AnyUseSuspenseQueryOptions_1: Expected.AnyUseSuspenseQueryOptions;
	DefinedInitialDataInfiniteOptions_1: Expected.DefinedInitialDataInfiniteOptions<string>;
	DefinedInitialDataOptions_1: Expected.DefinedInitialDataOptions;
	DefinedUseInfiniteQueryResult_1: Expected.DefinedUseInfiniteQueryResult;
	DefinedUseQueryResult_1: Expected.DefinedUseQueryResult;
	HydrationBoundary_1: JSX.Element;
	HydrationBoundary_2: Omit<Parameters<typeof Expected.HydrationBoundary>[0], 'children'>;
	HydrationBoundaryProps_1: Omit<Expected.HydrationBoundaryProps, 'children'>;
	IsRestoringProvider_1: Context<boolean>;
	QueriesOptions_1: Expected.QueriesOptions<never>;
	QueriesResults_1: Expected.QueriesResults<never>;
	QueryClientContext_1: Context<Expected.QueryClient | undefined>;
	QueryClientProvider_1: JSX.Element;
	QueryClientProvider_2: Omit<Parameters<typeof Expected.QueryClientProvider>[0], 'children'>;
	QueryClientProviderProps_1: Omit<Expected.QueryClientProviderProps, 'children'>;
	QueryErrorClearResetFunction_1: Expected.QueryErrorClearResetFunction;
	QueryErrorIsResetFunction_1: Expected.QueryErrorIsResetFunction;
	QueryErrorResetBoundary_1: JSX.Element;
	QueryErrorResetBoundary_2: Omit<
		Parameters<typeof Expected.QueryErrorResetBoundary>[0],
		'children'
	>;
	QueryErrorResetBoundaryFunction_1: Parameters<Expected.QueryErrorResetBoundaryFunction>;
	QueryErrorResetBoundaryFunction_2: OctaneNode;
	QueryErrorResetBoundaryProps_1: {
		children:
			OctaneNode | ((value: ReturnType<typeof Expected.useQueryErrorResetBoundary>) => OctaneNode);
	};
	QueryErrorResetFunction_1: Expected.QueryErrorResetFunction;
	SuspenseQueriesOptions_1: Expected.SuspenseQueriesOptions<never>;
	SuspenseQueriesResults_1: Expected.SuspenseQueriesResults<never>;
	UndefinedInitialDataInfiniteOptions_1: Expected.UndefinedInitialDataInfiniteOptions<string>;
	UndefinedInitialDataOptions_1: Expected.UndefinedInitialDataOptions;
	UnusedSkipTokenInfiniteOptions_1: Expected.UnusedSkipTokenInfiniteOptions<string>;
	UnusedSkipTokenOptions_1: Expected.UnusedSkipTokenOptions;
	UseBaseMutationResult_1: Expected.UseBaseMutationResult;
	UseBaseQueryOptions_1: Expected.UseBaseQueryOptions;
	UseBaseQueryResult_1: Expected.UseBaseQueryResult;
	UseInfiniteQueryOptions_1: Expected.UseInfiniteQueryOptions;
	UseInfiniteQueryResult_1: Expected.UseInfiniteQueryResult;
	UseMutateAsyncFunction_1: Expected.UseMutateAsyncFunction;
	UseMutateFunction_1: Expected.UseMutateFunction;
	UseMutationOptions_1: Expected.UseMutationOptions;
	UseMutationResult_1: Expected.UseMutationResult;
	UsePrefetchInfiniteQueryOptions_1: Expected.UsePrefetchInfiniteQueryOptions;
	UsePrefetchQueryOptions_1: Expected.UsePrefetchQueryOptions;
	UseQueryOptions_1: Expected.UseQueryOptions;
	UseQueryResult_1: Expected.UseQueryResult;
	UseSuspenseInfiniteQueryOptions_1: Expected.UseSuspenseInfiniteQueryOptions;
	UseSuspenseInfiniteQueryResult_1: Expected.UseSuspenseInfiniteQueryResult;
	UseSuspenseQueryOptions_1: Expected.UseSuspenseQueryOptions;
	UseSuspenseQueryResult_1: Expected.UseSuspenseQueryResult;
	infiniteQueryOptions_1: typeof Expected.infiniteQueryOptions;
	mutationOptions_1: typeof Expected.mutationOptions;
	queryOptions_1: typeof Expected.queryOptions;
	useInfiniteQuery_1: typeof Expected.useInfiniteQuery;
	useIsFetching_1: typeof Expected.useIsFetching;
	useIsMutating_1: typeof Expected.useIsMutating;
	useIsRestoring_1: typeof Expected.useIsRestoring;
	useMutation_1: typeof Expected.useMutation;
	useMutationState_1: ReturnType<
		typeof Expected.useMutationState<Expected.MutationState<number, Error, string, boolean>>
	>;
	usePrefetchInfiniteQuery_1: typeof Expected.usePrefetchInfiniteQuery;
	usePrefetchQuery_1: typeof Expected.usePrefetchQuery;
	useQueries_1: ReturnType<
		typeof Expected.useQueries<[{ queryFnData: number }, { queryFnData: string }]>
	>;
	useQuery_1: typeof Expected.useQuery;
	useQueryClient_1: typeof Expected.useQueryClient;
	useQueryErrorResetBoundary_1: typeof Expected.useQueryErrorResetBoundary;
	useSuspenseInfiniteQuery_1: typeof Expected.useSuspenseInfiniteQuery;
	useSuspenseQueries_1: ReturnType<
		typeof Expected.useSuspenseQueries<[{ queryFnData: number }, { queryFnData: string }]>
	>;
	useSuspenseQuery_1: typeof Expected.useSuspenseQuery;
	AnyDataTag_1: Expected.AnyDataTag;
	CancelOptions_1: Expected.CancelOptions;
	CancelledError_1: typeof Expected.CancelledError;
	DataTag_1: Expected.DataTag<string, string>;
	DefaultError_1: Expected.DefaultError;
	DefaultOptions_1: Expected.DefaultOptions;
	DefaultedInfiniteQueryObserverOptions_1: Expected.DefaultedInfiniteQueryObserverOptions;
	DefaultedQueryObserverOptions_1: Expected.DefaultedQueryObserverOptions;
	DefinedInfiniteQueryObserverResult_1: Expected.DefinedInfiniteQueryObserverResult;
	DefinedQueryObserverResult_1: Expected.DefinedQueryObserverResult;
	DehydrateOptions_1: Expected.DehydrateOptions;
	DehydratedState_1: Expected.DehydratedState;
	DistributiveOmit_1: Expected.DistributiveOmit<string, never>;
	EnsureInfiniteQueryDataOptions_1: Expected.EnsureInfiniteQueryDataOptions;
	EnsureQueryDataOptions_1: Expected.EnsureQueryDataOptions;
	FetchInfiniteQueryOptions_1: Expected.FetchInfiniteQueryOptions;
	FetchNextPageOptions_1: Expected.FetchNextPageOptions;
	FetchPreviousPageOptions_1: Expected.FetchPreviousPageOptions;
	FetchQueryOptions_1: Expected.FetchQueryOptions;
	FetchStatus_1: Expected.FetchStatus;
	GetNextPageParamFunction_1: Expected.GetNextPageParamFunction<string>;
	GetPreviousPageParamFunction_1: Expected.GetPreviousPageParamFunction<string>;
	HydrateOptions_1: Expected.HydrateOptions;
	InferDataFromTag_1: Expected.InferDataFromTag<string, never>;
	InferErrorFromTag_1: Expected.InferErrorFromTag<string, never>;
	InfiniteData_1: Expected.InfiniteData<string>;
	InfiniteQueryExecuteOptions_1: Expected.InfiniteQueryExecuteOptions;
	InfiniteQueryObserver_1: typeof Expected.InfiniteQueryObserver;
	InfiniteQueryObserverBaseResult_1: Expected.InfiniteQueryObserverBaseResult;
	InfiniteQueryObserverLoadingErrorResult_1: Expected.InfiniteQueryObserverLoadingErrorResult;
	InfiniteQueryObserverLoadingResult_1: Expected.InfiniteQueryObserverLoadingResult;
	InfiniteQueryObserverOptions_1: Expected.InfiniteQueryObserverOptions;
	InfiniteQueryObserverPendingResult_1: Expected.InfiniteQueryObserverPendingResult;
	InfiniteQueryObserverPlaceholderResult_1: Expected.InfiniteQueryObserverPlaceholderResult;
	InfiniteQueryObserverRefetchErrorResult_1: Expected.InfiniteQueryObserverRefetchErrorResult;
	InfiniteQueryObserverResult_1: Expected.InfiniteQueryObserverResult;
	InfiniteQueryObserverSuccessResult_1: Expected.InfiniteQueryObserverSuccessResult;
	InfiniteQueryPageParamsOptions_1: Expected.InfiniteQueryPageParamsOptions;
	InitialDataFunction_1: Expected.InitialDataFunction<string>;
	InitialPageParam_1: Expected.InitialPageParam;
	InvalidateOptions_1: Expected.InvalidateOptions;
	InvalidateQueryFilters_1: Expected.InvalidateQueryFilters;
	ManagedTimerId_1: Expected.ManagedTimerId;
	MutateFunction_1: Expected.MutateFunction;
	MutateFunctionRest_1: Expected.MutateFunctionRest;
	MutateOptions_1: Expected.MutateOptions;
	Mutation_1: typeof Expected.Mutation;
	MutationCache_1: typeof Expected.MutationCache;
	MutationCacheConfig_1: Expected.MutationCacheConfig;
	MutationCacheNotifyEvent_1: Expected.MutationCacheNotifyEvent;
	MutationFilters_1: Expected.MutationFilters;
	MutationFunction_1: Expected.MutationFunction;
	MutationFunctionContext_1: Expected.MutationFunctionContext;
	MutationKey_1: Expected.MutationKey;
	MutationMeta_1: Expected.MutationMeta;
	MutationObserver_1: typeof Expected.MutationObserver;
	MutationObserverBaseResult_1: Expected.MutationObserverBaseResult;
	MutationObserverErrorResult_1: Expected.MutationObserverErrorResult;
	MutationObserverIdleResult_1: Expected.MutationObserverIdleResult;
	MutationObserverLoadingResult_1: Expected.MutationObserverLoadingResult;
	MutationObserverOptions_1: Expected.MutationObserverOptions;
	MutationObserverResult_1: Expected.MutationObserverResult;
	MutationObserverSuccessResult_1: Expected.MutationObserverSuccessResult;
	MutationOptions_1: Expected.MutationOptions;
	MutationScope_1: Expected.MutationScope;
	MutationState_1: Expected.MutationState;
	MutationStatus_1: Expected.MutationStatus;
	NetworkMode_1: Expected.NetworkMode;
	NonUndefinedGuard_1: Expected.NonUndefinedGuard<string>;
	NotifyEvent_1: Expected.NotifyEvent;
	NotifyEventType_1: Expected.NotifyEventType;
	NotifyOnChangeProps_1: Expected.NotifyOnChangeProps;
	OmitKeyof_1: Expected.OmitKeyof<string, never>;
	Override_1: Expected.Override<string, string>;
	PlaceholderDataFunction_1: Expected.PlaceholderDataFunction;
	QueriesObserver_1: typeof Expected.QueriesObserver;
	QueriesObserverOptions_1: Expected.QueriesObserverOptions;
	QueriesPlaceholderDataFunction_1: Expected.QueriesPlaceholderDataFunction<string>;
	Query_1: typeof Expected.Query;
	QueryBooleanOption_1: Expected.QueryBooleanOption;
	QueryCache_1: typeof Expected.QueryCache;
	QueryCacheConfig_1: Expected.QueryCacheConfig;
	QueryCacheNotifyEvent_1: Expected.QueryCacheNotifyEvent;
	QueryClient_1: typeof Expected.QueryClient;
	QueryClientConfig_1: Expected.QueryClientConfig;
	QueryExecuteOptions_1: Expected.QueryExecuteOptions;
	QueryFilters_1: Expected.QueryFilters;
	QueryFunction_1: Expected.QueryFunction;
	QueryFunctionContext_1: Expected.QueryFunctionContext;
	QueryKey_1: Expected.QueryKey;
	QueryKeyHashFunction_1: Expected.QueryKeyHashFunction<never>;
	QueryKeyWithDataTag_1: Expected.QueryKeyWithDataTag;
	QueryMeta_1: Expected.QueryMeta;
	QueryObserver_1: typeof Expected.QueryObserver;
	QueryObserverBaseResult_1: Expected.QueryObserverBaseResult;
	QueryObserverLoadingErrorResult_1: Expected.QueryObserverLoadingErrorResult;
	QueryObserverLoadingResult_1: Expected.QueryObserverLoadingResult;
	QueryObserverOptions_1: Expected.QueryObserverOptions;
	QueryObserverPendingResult_1: Expected.QueryObserverPendingResult;
	QueryObserverPlaceholderResult_1: Expected.QueryObserverPlaceholderResult;
	QueryObserverRefetchErrorResult_1: Expected.QueryObserverRefetchErrorResult;
	QueryObserverResult_1: Expected.QueryObserverResult;
	QueryObserverSuccessResult_1: Expected.QueryObserverSuccessResult;
	QueryOptions_1: Expected.QueryOptions;
	QueryPersister_1: Expected.QueryPersister;
	QueryState_1: Expected.QueryState;
	QueryStatus_1: Expected.QueryStatus;
	RefetchOptions_1: Expected.RefetchOptions;
	RefetchQueryFilters_1: Expected.RefetchQueryFilters;
	Register_1: Expected.Register;
	ResetOptions_1: Expected.ResetOptions;
	ResultOptions_1: Expected.ResultOptions;
	SetDataOptions_1: Expected.SetDataOptions;
	SkipToken_1: Expected.SkipToken;
	StaleTime_1: Expected.StaleTime;
	StaleTimeFunction_1: Expected.StaleTimeFunction;
	ThrowOnError_1: Expected.ThrowOnError<string, string, string, never>;
	TimeoutCallback_1: Expected.TimeoutCallback;
	TimeoutProvider_1: Expected.TimeoutProvider;
	UnsetMarker_1: Expected.UnsetMarker;
	Updater_1: Expected.Updater<string, string>;
	WithRequired_1: Expected.WithRequired<string, never>;
	dataTagErrorSymbol_1: typeof Expected.dataTagErrorSymbol;
	dataTagSymbol_1: typeof Expected.dataTagSymbol;
	defaultScheduler_1: typeof Expected.defaultScheduler;
	defaultShouldDehydrateMutation_1: typeof Expected.defaultShouldDehydrateMutation;
	defaultShouldDehydrateQuery_1: typeof Expected.defaultShouldDehydrateQuery;
	dehydrate_1: typeof Expected.dehydrate;
	dehydrateQuery_1: typeof Expected.dehydrateQuery;
	environmentManager_1: typeof Expected.environmentManager;
	experimental_streamedQuery_1: typeof Expected.experimental_streamedQuery;
	focusManager_1: typeof Expected.focusManager;
	hashKey_1: typeof Expected.hashKey;
	hydrate_1: typeof Expected.hydrate;
	isCancelledError_1: typeof Expected.isCancelledError;
	isServer_1: typeof Expected.isServer;
	keepPreviousData_1: typeof Expected.keepPreviousData;
	matchMutation_1: typeof Expected.matchMutation;
	matchQuery_1: typeof Expected.matchQuery;
	noop_1: typeof Expected.noop;
	notifyManager_1: typeof Expected.notifyManager;
	onlineManager_1: typeof Expected.onlineManager;
	partialMatchKey_1: typeof Expected.partialMatchKey;
	replaceEqualDeep_1: typeof Expected.replaceEqualDeep;
	shouldThrowError_1: typeof Expected.shouldThrowError;
	skipToken_1: typeof Expected.skipToken;
	timeoutManager_1: typeof Expected.timeoutManager;
	unsetMarker_1: typeof Expected.unsetMarker;
	QueryErrorResetBoundaryValue_1: ReturnType<typeof Expected.useQueryErrorResetBoundary>;
}
