// This file is generated by scripts/error-codes/generate.mjs. Do not edit.
import {
	formatDevErrorMessage,
	formatProdErrorMessage,
	formatUnknownDevErrorMessage,
} from './error-message.js';

type ServerErrorArguments = {
	2: [];
	3: [unknown];
	4: [];
	5: [];
	6: [];
	7: [unknown];
	8: [unknown];
	9: [];
	10: [unknown];
	11: [];
	12: [unknown];
	23: [];
	30: [unknown];
	31: [];
	32: [unknown];
	34: [];
	35: [unknown];
	36: [];
	38: [];
	39: [];
	40: [];
	41: [];
	42: [];
	43: [];
	44: [];
	45: [];
	47: [unknown];
	48: [unknown];
	57: [];
	58: [];
	59: [unknown];
	60: [];
	65: [];
	68: [];
	69: [];
	70: [];
	71: [];
	73: [];
};

export function formatServerError<Code extends keyof ServerErrorArguments>(
	code: Code,
	...args: ServerErrorArguments[Code]
): string {
	if (process.env.NODE_ENV !== 'production') {
		switch (code) {
			case 2:
				return formatDevErrorMessage(
					'Children.only expected to receive a single element child.',
					args,
				);
			case 3:
				return formatDevErrorMessage(
					'Objects are not valid as an Octane child (found: %s). If you meant to render a collection of children, use an array instead.',
					args,
				);
			case 4:
				return formatDevErrorMessage(
					'cloneElement: the first argument must be an element (from createElement / JSX).',
					args,
				);
			case 5:
				return formatDevErrorMessage(
					'Can only set one of `children` or `props.dangerouslySetInnerHTML`.',
					args,
				);
			case 6:
				return formatDevErrorMessage(
					'`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`',
					args,
				);
			case 7:
				return formatDevErrorMessage(
					'`%s` is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 8:
				return formatDevErrorMessage(
					'`<%s>` is a void element tag and must neither have children nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 9:
				return formatDevErrorMessage(
					'Too many re-renders. Octane limits the number of renders to prevent an infinite loop.',
					args,
				);
			case 10:
				return formatDevErrorMessage(
					"lazy: expected the load() promise to resolve to a component function or a module with a component as its default export, got '%s'",
					args,
				);
			case 11:
				return formatDevErrorMessage(
					"A function wrapped in useEffectEvent can't be called during rendering.",
					args,
				);
			case 12:
				return formatDevErrorMessage('%s(): argument is not a Context nor a thenable', args);
			case 23:
				return formatDevErrorMessage('Server-rendered use() rejected', args);
			case 30:
				return formatDevErrorMessage('Invalid tag: %s', args);
			case 31:
				return formatDevErrorMessage(
					'If you supply `defaultValue` on a <textarea>, do not pass children.',
					args,
				);
			case 32:
				return formatDevErrorMessage(
					'octane SSR: a use(thenable) did not settle within %sms.',
					args,
				);
			case 34:
				return formatDevErrorMessage(
					'octane SSR: a root suspension no longer has resumable work.',
					args,
				);
			case 35:
				return formatDevErrorMessage(
					'octane SSR: %s root streaming passes completed without producing a shell.',
					args,
				);
			case 36:
				return formatDevErrorMessage(
					'octane SSR: a pending streamed boundary no longer has resumable work; its error escaped to an ancestor that was already flushed.',
					args,
				);
			case 38:
				return formatDevErrorMessage('The stream destination closed.', args);
			case 39:
				return formatDevErrorMessage(
					'octane SSR: destination.write() returned false but the destination cannot emit drain.',
					args,
				);
			case 40:
				return formatDevErrorMessage('The stream destination is closed.', args);
			case 41:
				return formatDevErrorMessage('octane SSR: pipe() may only be called once.', args);
			case 42:
				return formatDevErrorMessage('The render was aborted.', args);
			case 43:
				return formatDevErrorMessage('The stream consumer cancelled.', args);
			case 44:
				return formatDevErrorMessage('The readable stream is closed.', args);
			case 45:
				return formatDevErrorMessage('Server-rendered use() rejected (function)', args);
			case 47:
				return formatDevErrorMessage(
					'octane SSR: exceeded %s suspense passes — a use(thenable) never resolved. If promises are re-created on every render pass (e.g. created in an ancestor render and passed down through props), create them at their use() site or hoist them out of render.',
					args,
				);
			case 48:
				return formatDevErrorMessage(
					'octane SSR: %s consecutive streaming passes completed no boundary — a use(thenable) never resolved. If promises are re-created on every render pass (e.g. created in an ancestor render and passed down through props), create them at their use() site or hoist them out of render.',
					args,
				);
			case 57:
				return formatDevErrorMessage(
					'prerenderToNodeStream requires a Node.js runtime with process.getBuiltinModule; use prerender() in non-Node environments.',
					args,
				);
			case 58:
				return formatDevErrorMessage('Unsupported native-read compiler/runtime version.', args);
			case 59:
				return formatDevErrorMessage('%s requires an active server component.', args);
			case 60:
				return formatDevErrorMessage(
					'A component suspended without a Suspense boundary during synchronous server rendering. Use prerender() or a streaming renderer to await it.',
					args,
				);
			case 65:
				return formatDevErrorMessage(
					"Internal SSR invariant violated: ASYNC_SCOPE is not an extension of the active frame's async scope. Please file an Octane issue.",
					args,
				);
			case 68:
				return formatDevErrorMessage(
					'A signal control cannot join values from different document owners.',
					args,
				);
			case 69:
				return formatDevErrorMessage(
					'Independent Hydrate requires a build manifest in RenderOptions.',
					args,
				);
			case 70:
				return formatDevErrorMessage(
					'Independent Hydrate activation chunk is missing from the build manifest.',
					args,
				);
			case 71:
				return formatDevErrorMessage('Unsupported Octane server signal binding ABI.', args);
			case 73:
				return formatDevErrorMessage('Octane DOM bindings require unique list keys.', args);
			default:
				return formatUnknownDevErrorMessage(code);
		}
	}
	return formatProdErrorMessage(code, args);
}
