// @ts-check
/**
 * Cloudflare module Worker emitter.
 *
 * Octane's web-worker server build exports `createWebWorkerHandler()` and is
 * already self-contained. This final build step embeds the transformed HTML
 * template (and Rsbuild's late client asset map, when present) into a tiny
 * module Worker entry. Cloudflare serves `dist/client` asset-first; only misses
 * reach this handler, so the client index remains private under dist/server.
 */

/** @import { AdaptContext } from '@octanejs/app-core' */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CLIENT_ASSET_MAP = 'octane-client-assets.json';
const WORKER_ENTRY = 'worker.js';
const GENERATED_WORKER_HEADER = '// Auto-generated by @octanejs/adapter-cloudflare';

/**
 * @param {string} htmlTemplate
 * @param {Record<string, unknown> | undefined} clientAssets
 * @param {Record<string, unknown> | undefined} clientBuild
 * @param {Record<string, unknown> | undefined} independentHydration
 * @returns {string}
 */
function generateWorkerSource(htmlTemplate, clientAssets, clientBuild, independentHydration) {
	const options = {
		htmlTemplate,
		...(clientAssets === undefined ? null : { clientAssets }),
		...(clientBuild === undefined ? null : { clientBuild }),
		...(independentHydration === undefined ? null : { independentHydration }),
	};
	return `${GENERATED_WORKER_HEADER} — do not edit.
import { createWebWorkerHandler } from './entry.js';

let handler;

export default {
	async fetch(request, env, ctx) {
		try {
			handler ??= createWebWorkerHandler(${JSON.stringify(options, null, '\t')});
			return await handler(request, { env, ctx });
		} catch (error) {
			console.error('[octane] Cloudflare Worker handler error:', error);
			return new Response('Internal Server Error', { status: 500 });
		}
	},
};
`;
}

/**
 * @param {AdaptContext} ctx
 * @returns {Promise<void>}
 */
export async function emitCloudflareWorker(ctx) {
	const { clientDir, serverDir } = ctx;
	const log = ctx.log ?? ((/** @type {string} */ message) => console.log(message));
	const serverEntry = join(serverDir, 'entry.js');
	const htmlTemplate = join(serverDir, 'index.html');

	if (!existsSync(clientDir)) {
		throw new Error(
			`[@octanejs/adapter-cloudflare] Client build output not found at ${clientDir}.`,
		);
	}
	if (!existsSync(serverEntry)) {
		throw new Error(`[@octanejs/adapter-cloudflare] Server entry not found at ${serverEntry}.`);
	}
	if (!existsSync(htmlTemplate)) {
		throw new Error(
			`[@octanejs/adapter-cloudflare] Server HTML template not found at ${htmlTemplate}.`,
		);
	}

	const clientAssetMap = join(serverDir, CLIENT_ASSET_MAP);
	const clientAssets = existsSync(clientAssetMap)
		? JSON.parse(readFileSync(clientAssetMap, 'utf-8'))
		: undefined;
	const clientBuildFile = join(serverDir, 'octane-client-build.json');
	// This is required completed-build authority, unlike the optional asset map.
	// Fail at adaptation instead of publishing a Worker that fails on its first request.
	const clientBuild = JSON.parse(readFileSync(clientBuildFile, 'utf-8'));
	const independentHydrationFile = join(serverDir, 'octane-independent-hydration.json');
	const independentHydration = existsSync(independentHydrationFile)
		? JSON.parse(readFileSync(independentHydrationFile, 'utf-8'))
		: undefined;
	const output = join(serverDir, WORKER_ENTRY);
	if (existsSync(output) && !readFileSync(output, 'utf-8').startsWith(GENERATED_WORKER_HEADER)) {
		throw new Error(
			`[@octanejs/adapter-cloudflare] Refusing to replace ${output}: the server build already emitted worker.js. Configure asynchronous server chunks under a subdirectory.`,
		);
	}
	writeFileSync(
		output,
		generateWorkerSource(
			readFileSync(htmlTemplate, 'utf-8'),
			clientAssets,
			clientBuild,
			independentHydration,
		),
	);

	log(
		`[@octanejs/adapter-cloudflare] Worker entry written to ${join(ctx.outDir, 'server', WORKER_ENTRY)}`,
	);
}
