import * as Expected from '@tanstack/react-pacer';
type SyncWork = (value: number) => number;
type AsyncWork = (value: number) => Promise<number>;

export interface ExpectedContracts {
	PacerProvider: Omit<Parameters<typeof Expected.PacerProvider>[0], 'children'>;
	PacerProviderOptions: Expected.PacerProviderOptions;
	PacerProviderProps: Omit<Expected.PacerProviderProps, 'children'>;
	ReactAsyncBatcher: Omit<Expected.ReactAsyncBatcher<number>, 'Subscribe'>;
	ReactAsyncBatcherOptions: Omit<Expected.ReactAsyncBatcherOptions<number>, 'onUnmount'>;
	ReactAsyncDebouncer: Omit<Expected.ReactAsyncDebouncer<AsyncWork>, 'Subscribe'>;
	ReactAsyncDebouncerOptions: Omit<Expected.ReactAsyncDebouncerOptions<AsyncWork>, 'onUnmount'>;
	ReactAsyncQueuer: Omit<Expected.ReactAsyncQueuer<number>, 'Subscribe'>;
	ReactAsyncQueuerOptions: Omit<Expected.ReactAsyncQueuerOptions<number>, 'onUnmount'>;
	ReactAsyncRateLimiter: Omit<Expected.ReactAsyncRateLimiter<AsyncWork>, 'Subscribe'>;
	ReactAsyncRateLimiterOptions: Omit<Expected.ReactAsyncRateLimiterOptions<AsyncWork>, 'onUnmount'>;
	ReactAsyncThrottler: Omit<Expected.ReactAsyncThrottler<AsyncWork>, 'Subscribe'>;
	ReactAsyncThrottlerOptions: Omit<Expected.ReactAsyncThrottlerOptions<AsyncWork>, 'onUnmount'>;
	ReactBatcher: Omit<Expected.ReactBatcher<number>, 'Subscribe'>;
	ReactBatcherOptions: Omit<Expected.ReactBatcherOptions<number>, 'onUnmount'>;
	ReactDebouncer: Omit<Expected.ReactDebouncer<SyncWork>, 'Subscribe'>;
	ReactDebouncerOptions: Omit<Expected.ReactDebouncerOptions<SyncWork>, 'onUnmount'>;
	ReactQueuer: Omit<Expected.ReactQueuer<number>, 'Subscribe'>;
	ReactQueuerOptions: Omit<Expected.ReactQueuerOptions<number>, 'onUnmount'>;
	ReactRateLimiter: Omit<Expected.ReactRateLimiter<SyncWork>, 'Subscribe'>;
	ReactRateLimiterOptions: Omit<Expected.ReactRateLimiterOptions<SyncWork>, 'onUnmount'>;
	ReactThrottler: Omit<Expected.ReactThrottler<SyncWork>, 'Subscribe'>;
	ReactThrottlerOptions: Omit<Expected.ReactThrottlerOptions<SyncWork>, 'onUnmount'>;
	useAsyncBatchedCallback: ReturnType<typeof Expected.useAsyncBatchedCallback<number>>;
	useAsyncBatcher: Omit<ReturnType<typeof Expected.useAsyncBatcher<number>>, 'Subscribe'>;
	useAsyncDebouncedCallback: ReturnType<typeof Expected.useAsyncDebouncedCallback<AsyncWork>>;
	useAsyncDebouncer: Omit<ReturnType<typeof Expected.useAsyncDebouncer<AsyncWork>>, 'Subscribe'>;
	useAsyncQueuedState: ReturnType<typeof Expected.useAsyncQueuedState<number>>[0];
	useAsyncQueuer: Omit<ReturnType<typeof Expected.useAsyncQueuer<number>>, 'Subscribe'>;
	useAsyncRateLimitedCallback: ReturnType<typeof Expected.useAsyncRateLimitedCallback<AsyncWork>>;
	useAsyncRateLimiter: Omit<
		ReturnType<typeof Expected.useAsyncRateLimiter<AsyncWork>>,
		'Subscribe'
	>;
	useAsyncThrottledCallback: ReturnType<typeof Expected.useAsyncThrottledCallback<AsyncWork>>;
	useAsyncThrottler: Omit<ReturnType<typeof Expected.useAsyncThrottler<AsyncWork>>, 'Subscribe'>;
	useBatchedCallback: ReturnType<typeof Expected.useBatchedCallback<number>>;
	useBatcher: Omit<ReturnType<typeof Expected.useBatcher<number>>, 'Subscribe'>;
	useDebouncedCallback: ReturnType<typeof Expected.useDebouncedCallback<SyncWork>>;
	useDebouncedState: ReturnType<typeof Expected.useDebouncedState<number>>[0];
	useDebouncedValue: ReturnType<typeof Expected.useDebouncedValue<number>>[0];
	useDebouncer: Omit<ReturnType<typeof Expected.useDebouncer<SyncWork>>, 'Subscribe'>;
	useDefaultPacerOptions: ReturnType<typeof Expected.useDefaultPacerOptions>;
	usePacerContext: ReturnType<typeof Expected.usePacerContext>;
	useQueuedState: ReturnType<typeof Expected.useQueuedState<number>>[0];
	useQueuedValue: ReturnType<typeof Expected.useQueuedValue<number>>[0];
	useQueuer: Omit<ReturnType<typeof Expected.useQueuer<number>>, 'Subscribe'>;
	useRateLimitedCallback: ReturnType<typeof Expected.useRateLimitedCallback<SyncWork>>;
	useRateLimitedState: ReturnType<typeof Expected.useRateLimitedState<number>>[0];
	useRateLimitedValue: ReturnType<typeof Expected.useRateLimitedValue<number>>[0];
	useRateLimiter: Omit<ReturnType<typeof Expected.useRateLimiter<SyncWork>>, 'Subscribe'>;
	useThrottledCallback: ReturnType<typeof Expected.useThrottledCallback<SyncWork>>;
	useThrottledState: ReturnType<typeof Expected.useThrottledState<number>>[0];
	useThrottledValue: ReturnType<typeof Expected.useThrottledValue<number>>[0];
	useThrottler: Omit<ReturnType<typeof Expected.useThrottler<SyncWork>>, 'Subscribe'>;
	AnyAsyncFunction: Expected.AnyAsyncFunction;
	AnyFunction: Expected.AnyFunction;
	AsyncBatcherOptions: Expected.AsyncBatcherOptions<number>;
	AsyncBatcherState: Expected.AsyncBatcherState<number>;
	AsyncDebouncerOptions: Expected.AsyncDebouncerOptions<AsyncWork>;
	AsyncDebouncerState: Expected.AsyncDebouncerState<AsyncWork>;
	AsyncQueuerOptions: Expected.AsyncQueuerOptions<number>;
	AsyncQueuerState: Expected.AsyncQueuerState<number>;
	AsyncRateLimiterOptions: Expected.AsyncRateLimiterOptions<AsyncWork>;
	AsyncRateLimiterState: Expected.AsyncRateLimiterState<AsyncWork>;
	AsyncRetryerOptions: Expected.AsyncRetryerOptions<AsyncWork>;
	AsyncRetryerState: Expected.AsyncRetryerState<AsyncWork>;
	AsyncThrottlerOptions: Expected.AsyncThrottlerOptions<AsyncWork>;
	AsyncThrottlerState: Expected.AsyncThrottlerState<AsyncWork>;
	BatcherOptions: Expected.BatcherOptions<number>;
	BatcherState: Expected.BatcherState<number>;
	DebouncerOptions: Expected.DebouncerOptions<SyncWork>;
	DebouncerState: Expected.DebouncerState<SyncWork>;
	OptionalKeys: Expected.OptionalKeys<{ value: number }, 'value'>;
	PacerDevtoolsWirePayload: Expected.PacerDevtoolsWirePayload;
	PacerEventMap: Expected.PacerEventMap;
	PacerEventName: Expected.PacerEventName;
	QueuePosition: Expected.QueuePosition;
	QueuerOptions: Expected.QueuerOptions<number>;
	QueuerState: Expected.QueuerState<number>;
	RateLimiterOptions: Expected.RateLimiterOptions<SyncWork>;
	RateLimiterState: Expected.RateLimiterState;
	ThrottlerOptions: Expected.ThrottlerOptions<SyncWork>;
	ThrottlerState: Expected.ThrottlerState<SyncWork>;
}
