// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
export type TooltipPositionContextType = {
    isFlippedVertically: boolean;
    isFlippedHorizontally: boolean;
};
export declare const TooltipPositionProvider: import("octane").Context<TooltipPositionContextType>;
/**
 * Octane deliberately has no render-prop `Context.Consumer` (see
 * docs/differences-from-react.md); reading `.Consumer` returns `undefined` and
 * warns in development. Keep upstream's render-prop API by reading the context
 * with `useContext` instead.
 */
export declare function TooltipPositionConsumer({ children, }: {
    children: (value: TooltipPositionContextType) => OctaneNode;
}): import("react").JSX.Element;
export declare const useTooltipPosition: () => TooltipPositionContextType;
